# Generated by Django 4.2.7 on 2023-12-22 18:29

from django.db import migrations, models
import main.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_completed_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='_hash',
            field=models.CharField(default=main.functions.get_random_string32, max_length=256),
        ),
    ]
