# Generated by Django 4.2.7 on 2023-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
