# Generated by Django 4.2.7 on 2023-12-09 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_group_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
