# Generated by Django 4.2.8 on 2023-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_completed_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='_hash',
            field=models.CharField(default='WRW5cXE5OWzAEkFcBdf4lf9cFu2UeCQJ', max_length=256),
        ),
    ]
